version: 0.0
os: linux
files:
  - source: /app
    destination: /var/www/html
hooks:
   ApplicationStop
     - location: Scripts/applicationstop.sh
   ApplicationStart
     - location: Scripts/applicationstart.sh
   ValidateService:
     - location: Scripts/validateservice.sh